/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simp;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Wojcisz
 */

public class NewJFrame extends javax.swing.JFrame {

    int imgHeight = 300;
    int imgWidth = 300;
    String fileName;
    String path;
    BufferedImage img = new BufferedImage(imgWidth,imgHeight,BufferedImage.TYPE_INT_RGB);
    Graphics2D gfx =null;
    File file;
    BufferedImage imgOperations = new BufferedImage(100, 200,BufferedImage.TYPE_BYTE_INDEXED);
    boolean bRefreshing = true;
    boolean drawable =false;
    Color kolorTla = Color.GRAY;


    public NewJFrame() {
        super("SIMP - Student Image Manipulation Program");
        for (int x = 0; x < img.getWidth(); x++) { // biale tlo
            for (int y = 0; y < img.getHeight(); y++) {
            img.setRGB(x, y, 0xffffff);
            }
        }
        initComponents();
        gfx = (Graphics2D) jPanel.getGraphics();
        jPanel.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
        if(drawable ){
            int x = e.getX();
            int y = e.getY();
            
            for(int i = 0;i<3;i++){
                for(int j = 0;j<3;j++){
                if(((x+1)<imgWidth) && ((y+1)<imgHeight)){
                    if((x>0)&&(y>0)){
                    Color drawableColor = gfx.getColor();
                    int colorInt = drawableColor.getRGB();
                    img.setRGB(x-1+i, y-1+j, colorInt );
                    }
                }
            }
        }
     }
  }});     
        int timerTimeInMilliSeconds = 10;
        javax.swing.Timer timer = new javax.swing.Timer(timerTimeInMilliSeconds, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if(bRefreshing){
                gfx.drawImage(img, 0, 0, null);
            }
        }
        });
        timer.start();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileOpenChooser = new javax.swing.JFileChooser();
        colorChooser = new javax.swing.JColorChooser();
        jPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSharpen = new javax.swing.JMenuItem();
        menuBlur = new javax.swing.JMenuItem();
        menuRotateClockwise = new javax.swing.JMenuItem();
        menuRotateCounterClockwise = new javax.swing.JMenuItem();
        menuLighten = new javax.swing.JMenuItem();
        menuDim = new javax.swing.JMenuItem();
        menuCorrR = new javax.swing.JMenuItem();
        menuCorrG = new javax.swing.JMenuItem();
        menuCorrB = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuPickColor = new javax.swing.JMenuItem();
        menuPencil = new javax.swing.JMenuItem();
        menuClearAll = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        fileOpenChooser.setDialogTitle("Wybierz obrazek");
        fileOpenChooser.setFileFilter(new menuOpenFilter());

        colorChooser.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setName("calypanel"); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenuBar1.setName("pasek"); // NOI18N

        jMenu1.setText("Plik");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                NewJFrame.this.menuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MenuSelected(evt);
            }
        });
        jMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menuKeyReleased(evt);
            }
        });

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setText("Otwórz");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpen);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setText("Zapisz");
        menuSave.setActionCommand("jMenuItem3");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave);

        menuAbout.setText("O autorach");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbout);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setText("Koniec");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edytuj");
        jMenu2.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                menu2KeyReleased(evt);
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                menu2Deselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu2Selected(evt);
            }
        });

        menuSharpen.setText("Wyostrz");
        menuSharpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSharpenActionPerformed(evt);
            }
        });
        jMenu2.add(menuSharpen);

        menuBlur.setText("Rozmyj");
        menuBlur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBlurActionPerformed(evt);
            }
        });
        jMenu2.add(menuBlur);

        menuRotateClockwise.setText("Obrót w prawo o 90 stopni");
        menuRotateClockwise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRotateClockwiseActionPerformed(evt);
            }
        });
        jMenu2.add(menuRotateClockwise);

        menuRotateCounterClockwise.setText("Obrót w lewo o 90 stopni");
        menuRotateCounterClockwise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRotateCounterClockwiseActionPerformed(evt);
            }
        });
        jMenu2.add(menuRotateCounterClockwise);

        menuLighten.setText("Rozjaśnij");
        menuLighten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLightenActionPerformed(evt);
            }
        });
        jMenu2.add(menuLighten);

        menuDim.setText("Przyciemnij");
        menuDim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDimActionPerformed(evt);
            }
        });
        jMenu2.add(menuDim);

        menuCorrR.setText("Korekta R");
        menuCorrR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCorrRActionPerformed(evt);
            }
        });
        jMenu2.add(menuCorrR);

        menuCorrG.setText("Korekta G");
        menuCorrG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCorrGActionPerformed(evt);
            }
        });
        jMenu2.add(menuCorrG);

        menuCorrB.setText("Korekta B");
        menuCorrB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCorrBActionPerformed(evt);
            }
        });
        jMenu2.add(menuCorrB);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Rysuj");
        jMenu5.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                menu3KeyReleased(evt);
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                menu3Deselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu3Selected(evt);
            }
        });

        menuPickColor.setText("Wybierz kolor");
        menuPickColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPickColorActionPerformed(evt);
            }
        });
        jMenu5.add(menuPickColor);

        menuPencil.setText("Ołówek");
        menuPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPencilActionPerformed(evt);
            }
        });
        jMenu5.add(menuPencil);

        menuClearAll.setText("Wyczyść wszystko");
        menuClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearAllActionPerformed(evt);
            }
        });
        jMenu5.add(menuClearAll);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Skin");
        jMenu3.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                jMenu3MenuKeyReleased(evt);
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });

        jMenuItem1.setText("Black");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Yellow");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Blue");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Gray");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	
	private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
            int returnVal = fileOpenChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                file = fileOpenChooser.getSelectedFile();
                fileName = fileOpenChooser.getName(file);
                path = file.getAbsolutePath();
                try {         
                    img = ImageIO.read(file);
                    imgHeight = img.getHeight();
                    imgWidth = img.getWidth();
                    Dimension d = new Dimension(imgWidth,imgHeight);
                    jPanel.setSize(d);
                    jPanel.setBackground(kolorTla);
                    gfx.drawImage(img, 0, 0, null);
                    //bRefreshing=true;
                    System.out.println("Otworzono plik: "+path);
                    //jPanel.updateUI();
                } 
                catch (IOException ex) {

                    System.out.println("Nie udało się otworzyć pliku." + path);

                }
            } 
            else {
                    System.out.println("Anulowano wybór pliku przez użytkownika.");
            }
    }//GEN-LAST:event_menuOpenActionPerformed
 
    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed

        String fileExtension = "BMP"; // default png

        // get file extension
        int i = fileName.lastIndexOf('.');
        if (i > 0) {
            fileExtension = fileName.substring(i+1);
        }
                try {
                    ImageIO.write(img, fileExtension, new File(path));
                    System.out.println("Zapisano plik: " + path);

                } 
                catch (IOException ex) {
                    ex.printStackTrace();
                    System.out.println("Nie udało się zapisać pliku.");
                } 
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Autorzy :\nWojciech Zgliniecki\nKarol Dworakowski ");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuSharpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSharpenActionPerformed
        imgOperations = img;
        Kernel kernel = new Kernel(3, 3, new float[] { -1, -1, -1, -1, 9, -1, -1,
        -1, -1 });
        BufferedImageOp op = new ConvolveOp(kernel);
        img = imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuSharpenActionPerformed
    
    private void menuBlurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBlurActionPerformed
        imgOperations = img;
        Kernel kernel = new Kernel(3, 3, new float[] { 1f / 9f, 1f / 9f, 1f / 9f,
        1f / 9f, 1f / 9f, 1f / 9f, 1f / 9f, 1f / 9f, 1f / 9f });
        BufferedImageOp op = new ConvolveOp(kernel);
        img=imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuBlurActionPerformed

    private void menuRotateClockwiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRotateClockwiseActionPerformed
        imgOperations = img;
        AffineTransform tx = new AffineTransform();
        tx.rotate(Math.PI/2, imgOperations.getWidth() / 2, imgOperations.getHeight() / 2);

        AffineTransformOp op = new AffineTransformOp(tx,AffineTransformOp.TYPE_BILINEAR);
        img=imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuRotateClockwiseActionPerformed

    private void menuRotateCounterClockwiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRotateCounterClockwiseActionPerformed
        imgOperations = img;
        AffineTransform tx = new AffineTransform();
        tx.rotate(-Math.PI/2, imgOperations.getWidth() / 2, imgOperations.getHeight() / 2);

        AffineTransformOp op = new AffineTransformOp(tx,AffineTransformOp.TYPE_BILINEAR);
        img=imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuRotateCounterClockwiseActionPerformed


    
    
    
    
    private void menuLightenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLightenActionPerformed
        // rozjasnianie
        int blue = 0;
        int green = 0;
        int red = 0;
        int alpha = 0;
        int color = 0;
        
        for( int i = 0; i < img.getHeight()-1; i++ )
            for( int j = 0; j < img.getWidth()-1; j++ ){
                color = img.getRGB(i, j); // dostajemy kolor w postaci 32 bitowej liczby ze znakiem
                // pierwsze 8 bitow to B, kolejne G itd.
                // bierzemy poszczegolne kolory
                blue = color & 0xff;
                green = (color & 0xff00) >> 8;
                red = (color & 0xff0000) >> 16;
                alpha = (color & 0xff000000) >>> 24; // >>> ze wzgledu na znak ?? #stackoverflow
                // tutaj robimy operacje na kolorach
                
                   if (red < 3 && red != 0) {
                     red = 3;
                   } else {
                     red = (int) (red / 0.7);
                     red = (red > 255) ? 255 : red;
                   }

                   if (blue< 3 && blue!= 0) {
                     blue= 3;
                   } else {
                     blue= (int) (blue/ 0.7);
                     blue= (blue> 255) ? 255 : blue;
                   }

                   if (green< 3 && green!= 0) {
                     green= 3;
                   } else {
                     green= (int) (green/ 0.7);
                     green= (green> 255) ? 255 : green;
                   }
                color = blue | green << 8 | red << 16 | alpha << 24; // skladamy kolor do kupy
                img.setRGB(i, j, color);
            }
        //bRefreshing = true;
        //trzeba tylko raz go narysowac
        gfx.drawImage(img, 0, 0, null);
    }//GEN-LAST:event_menuLightenActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuPencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPencilActionPerformed
        drawable= !drawable;
	}//GEN-LAST:event_menuPencilActionPerformed

    private void menuClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearAllActionPerformed
        jPanel.removeAll();
        jPanel.updateUI();
        imgHeight = 300;
        imgWidth = 300;
        img = new BufferedImage(imgWidth,imgHeight,BufferedImage.TYPE_INT_RGB );
                for (int x = 0; x < img.getWidth(); x++) { // biale tlo
            for (int y = 0; y < img.getHeight(); y++) {
            img.setRGB(x, y, 0xffffff);
            }
        }
        Dimension d = new Dimension(imgWidth,imgHeight);
        jPanel.setSize(d);
    }//GEN-LAST:event_menuClearAllActionPerformed
	
    private void menuPickColorActionPerformed(java.awt.event.ActionEvent evt) {                                                                                        
        Color currentColor=gfx.getColor();
        Color change = JColorChooser.showDialog(null, "Wybór koloru Ołówka", currentColor);
        gfx.setColor(change);
    }                                               

    //ta litania poleceń służy do zapewnienia odpowiedniego odświeżania
    private void menuDeselected(javax.swing.event.MenuEvent evt) {                                
        bRefreshing=true;
    }                               
	
	private void menu2Deselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuDeselected
        bRefreshing=true;
    }//GEN-LAST:event_menuDeselected

    private void menuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuKeyReleased
        bRefreshing=true;
    }//GEN-LAST:event_menuKeyReleased

    private void menu2KeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menu2KeyReleased
        bRefreshing=true;
    }//GEN-LAST:event_menu2KeyReleased
        
    private void menu3KeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menu3KeyReleased
       bRefreshing=true; 
    }//GEN-LAST:event_menu3KeyReleased

    private void menu3Deselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu3Deselected
        bRefreshing=true;
    }//GEN-LAST:event_menu3Deselected

	private void MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MenuSelected
        bRefreshing=false;
    }//GEN-LAST:event_MenuSelected

    private void menu2Selected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu2Selected
        bRefreshing=false;
    }//GEN-LAST:event_menu2Selected

    private void menu3Selected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu3Selected
        bRefreshing=false;
    }//GEN-LAST:event_menu3Selected

    private void menuDimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDimActionPerformed

        int blue = 0;
        int green = 0;
        int red = 0;
        int alpha = 0;
        int color = 0;
        
        for( int i = 0; i < img.getHeight()-1; i++ )
            for( int j = 0; j < img.getWidth()-1; j++ ){
                color = img.getRGB(i, j); // dostajemy kolor w postaci 32 bitowej liczby ze znakiem
                // pierwsze 8 bitow to B, kolejne G itd.
                // bierzemy poszczegolne kolory
                blue = color & 0xff;
                green = (color & 0xff00) >> 8;
                red = (color & 0xff0000) >> 16;
                alpha = (color & 0xff000000) >>> 24; // >>> ze wzgledu na znak ?? #stackoverflow
                // tutaj robimy operacje na kolorach
                blue= (int) (blue* 0.7);
                green= (int) (green* 0.7);
                red= (int) (red* 0.7);
                
                color = blue | green << 8 | red << 16 | alpha << 24; // skladamy kolor do kupy
                img.setRGB(i, j, color);
            }
        //bRefreshing = true;
        //trzeba tylko raz go narysowac
        gfx.drawImage(img, 0, 0, null);
    }//GEN-LAST:event_menuDimActionPerformed

    private void menuCorrBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCorrBActionPerformed

        int blue = 0;
        int green = 0;
        int red = 0;
        int alpha = 0;
        int color = 0;
        
        for( int i = 0; i < img.getHeight()-1; i++ )
            for( int j = 0; j < img.getWidth()-1; j++ ){
                color = img.getRGB(i, j); // dostajemy kolor w postaci 32 bitowej liczby ze znakiem
                // pierwsze 8 bitow to B, kolejne G itd.
                // bierzemy poszczegolne kolory
                blue = color & 0xff;
                green = (color & 0xff00) >> 8;
                red = (color & 0xff0000) >> 16;
                alpha = (color & 0xff000000) >>> 24; // >>> ze wzgledu na znak ?? #stackoverflow
                // tutaj robimy operacje na kolorach
                red = 0;
                green = 0;
                color = blue | green << 8 | red << 16 | alpha << 24; // skladamy kolor do kupy
                img.setRGB(i, j, color);
            }
        //bRefreshing = true;
        //trzeba tylko raz go narysowac
        gfx.drawImage(img, 0, 0, null);
    }//GEN-LAST:event_menuCorrBActionPerformed

    private void menuCorrRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCorrRActionPerformed
          int blue = 0;
        int green = 0;
        int red = 0;
        int alpha = 0;
        int color = 0;
        
        for( int i = 0; i < img.getHeight()-1; i++ )
            for( int j = 0; j < img.getWidth()-1; j++ ){
                color = img.getRGB(i, j); // dostajemy kolor w postaci 32 bitowej liczby ze znakiem
                // pierwsze 8 bitow to B, kolejne G itd.
                // bierzemy poszczegolne kolory
                blue = color & 0xff;
                green = (color & 0xff00) >> 8;
                red = (color & 0xff0000) >> 16;
                alpha = (color & 0xff000000) >>> 24; // >>> ze wzgledu na znak ?? #stackoverflow
                // tutaj robimy operacje na kolorach
                blue = 0;
                green = 0;
                color = blue | green << 8 | red << 16 | alpha << 24; // skladamy kolor do kupy
                img.setRGB(i, j, color);
            }
        //bRefreshing = true;
        //trzeba tylko raz go narysowac
        gfx.drawImage(img, 0, 0, null);
    }//GEN-LAST:event_menuCorrRActionPerformed

    private void menuCorrGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCorrGActionPerformed
          int blue = 0;
        int green = 0;
        int red = 0;
        int alpha = 0;
        int color = 0;
//        Color curColor;
//        Color currentColor=gfx.getColor();
//        Color change = JColorChooser.showDialog(null, "Wybór koloru Ołówka", currentColor);
//        gfx.setColor(change);
        
        for( int i = 0; i < img.getHeight()-1; i++ )
            for( int j = 0; j < img.getWidth()-1; j++ ){
                color = img.getRGB(i, j); // dostajemy kolor w postaci 32 bitowej liczby ze znakiem
                // pierwsze 8 bitow to B, kolejne G itd.
                // bierzemy poszczegolne kolory
                blue = color & 0xff;
                green = (color & 0xff00) >> 8;
                red = (color & 0xff0000) >> 16;
                alpha = (color & 0xff000000) >>> 24; // >>> ze wzgledu na znak ?? #stackoverflow
                // tutaj robimy operacje na kolorach
                //Color change = JColorChooser.showDialog(null, "Wybór koloru ", curColor);
                red = 0;
                blue = 0;
                color = blue | green << 8 | red << 16 | alpha << 24; // skladamy kolor
                img.setRGB(i, j, color);
            }
        //bRefreshing = true;
        //trzeba tylko raz go narysowac
        gfx.drawImage(img, 0, 0, null);
    }//GEN-LAST:event_menuCorrGActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        kolorTla=Color.BLACK;
        jPanel.setBackground(kolorTla);
        jPanel.updateUI();
        bRefreshing=true;

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        kolorTla=Color.YELLOW;
        jPanel.setBackground(kolorTla);
        jPanel.updateUI();
        bRefreshing=true;

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        kolorTla=Color.BLUE;
        jPanel.setBackground(kolorTla);
        jPanel.updateUI();
        bRefreshing=true;
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        kolorTla=Color.GRAY;
        jPanel.setBackground(kolorTla);
        jPanel.updateUI();
        bRefreshing=true;
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3MenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuDeselected
        // TODO add your handling code here:
                bRefreshing=false;

    }//GEN-LAST:event_jMenu3MenuDeselected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        // TODO add your handling code here:
                bRefreshing=false;

    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu3MenuKeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu3MenuKeyReleased
        // TODO add your handling code here:
                bRefreshing=false;

    }//GEN-LAST:event_jMenu3MenuKeyReleased
    //koniec litanii

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JFileChooser fileOpenChooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuBlur;
    private javax.swing.JMenuItem menuClearAll;
    private javax.swing.JMenuItem menuCorrB;
    private javax.swing.JMenuItem menuCorrG;
    private javax.swing.JMenuItem menuCorrR;
    private javax.swing.JMenuItem menuDim;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLighten;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuPencil;
    private javax.swing.JMenuItem menuPickColor;
    private javax.swing.JMenuItem menuRotateClockwise;
    private javax.swing.JMenuItem menuRotateCounterClockwise;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSharpen;
    // End of variables declaration//GEN-END:variables
}
