/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simp;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Wojcisz
 */

public class NewJFrame extends javax.swing.JFrame {

    int imgHeight = 300;
    int imgWidth = 300;
    String fileName;
    String path;
    BufferedImage img = new BufferedImage(imgWidth,imgHeight,BufferedImage.TYPE_INT_ARGB );
    Graphics2D gfx =null;
    File file;
    BufferedImage imgOperations = new BufferedImage(100, 200,BufferedImage.TYPE_BYTE_INDEXED);
    boolean bRefreshing = true;
    boolean drawable =false;

    public NewJFrame() {
        super("SIMP - Student Image Manipulation Program");
        initComponents();
        gfx = (Graphics2D) jPanel.getGraphics();
        jPanel.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
        if(drawable ){
            int x = e.getX();
            int y = e.getY();
            
            for(int i = 0;i<3;i++){
                for(int j = 0;j<3;j++){
                if(((x+1)<imgWidth) && ((y+1)<imgHeight)){
                    if((x>0)&&(y>0)){
                    Color drawableColor = gfx.getColor();
                    int colorInt = drawableColor.getRGB();
                    img.setRGB(x-1+i, y-1+j, colorInt );
                    }
                }
            }
        }
     }
  }});     
        int timerTimeInMilliSeconds = 10;
        javax.swing.Timer timer = new javax.swing.Timer(timerTimeInMilliSeconds, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if(bRefreshing){
                gfx.drawImage(img, 0, 0, null);
            }
        }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileOpenChooser = new javax.swing.JFileChooser();
        colorChooser = new javax.swing.JColorChooser();
        jPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSharpen = new javax.swing.JMenuItem();
        menuBlur = new javax.swing.JMenuItem();
        menuRotateClockwise = new javax.swing.JMenuItem();
        menuRotateCounterClockwise = new javax.swing.JMenuItem();
        menuColorCorrection = new javax.swing.JMenuItem();
        menuHueSaturation = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuPickColor = new javax.swing.JMenuItem();
        menuPencil = new javax.swing.JMenuItem();
        menuClearAll = new javax.swing.JMenuItem();

        fileOpenChooser.setDialogTitle("Wybierz obrazek");
        fileOpenChooser.setFileFilter(new menuOpenFilter());

        colorChooser.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Plik");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                NewJFrame.this.menuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MenuSelected(evt);
            }
        });
        jMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menuKeyReleased(evt);
            }
        });

        menuOpen.setText("Otwórz");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpen);

        menuSave.setText("Zapisz");
        menuSave.setActionCommand("jMenuItem3");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave);

        menuAbout.setText("O autorach");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbout);

        menuExit.setText("Koniec");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edytuj");
        jMenu2.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                menu2KeyReleased(evt);
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                menu2Deselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu2Selected(evt);
            }
        });

        menuSharpen.setText("Wyostrz");
        menuSharpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSharpenActionPerformed(evt);
            }
        });
        jMenu2.add(menuSharpen);

        menuBlur.setText("Rozmyj");
        menuBlur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBlurActionPerformed(evt);
            }
        });
        jMenu2.add(menuBlur);

        menuRotateClockwise.setText("Obrót w prawo o 90 stopni");
        menuRotateClockwise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRotateClockwiseActionPerformed(evt);
            }
        });
        jMenu2.add(menuRotateClockwise);

        menuRotateCounterClockwise.setText("Obrót w lewo o 90 stopni");
        menuRotateCounterClockwise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRotateCounterClockwiseActionPerformed(evt);
            }
        });
        jMenu2.add(menuRotateCounterClockwise);

        menuColorCorrection.setText("Korekta kolorystyczna");
        menuColorCorrection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorCorrectionActionPerformed(evt);
            }
        });
        jMenu2.add(menuColorCorrection);

        menuHueSaturation.setText("Jasność i kontrast");
        menuHueSaturation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHueSaturationActionPerformed(evt);
            }
        });
        jMenu2.add(menuHueSaturation);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Rysuj");
        jMenu5.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                menu3KeyReleased(evt);
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                menu3Deselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu3Selected(evt);
            }
        });

        menuPickColor.setText("Wybierz kolor");
        menuPickColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPickColorActionPerformed(evt);
            }
        });
        jMenu5.add(menuPickColor);

        menuPencil.setText("Ołówek");
        menuPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPencilActionPerformed(evt);
            }
        });
        jMenu5.add(menuPencil);

        menuClearAll.setText("Wyczyść wszystko");
        menuClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearAllActionPerformed(evt);
            }
        });
        jMenu5.add(menuClearAll);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	
	private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
            int returnVal = fileOpenChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                file = fileOpenChooser.getSelectedFile();
                fileName = fileOpenChooser.getName(file);
                path = file.getAbsolutePath();
                try {         
                    img = ImageIO.read(file);
                    imgHeight = img.getHeight();
                    imgWidth = img.getWidth();
                    Dimension d = new Dimension(imgWidth,imgHeight);
                    jPanel.setSize(d);
                    gfx.drawImage(img, 0, 0, null);
                    System.out.println("Otworzono plik: "+path);
                } 
                catch (IOException ex) {
                    System.out.println("Nie udało się otworzyć pliku."+path);
                }
            } 
            else {
                    System.out.println("Anulowano wybór pliku przez użytkownika.");
            }
    }//GEN-LAST:event_menuOpenActionPerformed
 
    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        String fileExtension = "BMP"; // default png
        // get file extension
        int i = fileName.lastIndexOf('.');
        if (i > 0) {
            fileExtension = fileName.substring(i+1);
        }
                try {
                    ImageIO.write(img, fileExtension, new File(path));
                    System.out.println("Zapisano plik: "+path);
                } 
                catch (IOException ex) {
                    ex.printStackTrace();
                    System.out.println("Nie udało się zapisać pliku.");
                } 
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Autorzy :\nWojciech Zgliniecki\nKarol Dworakowski ");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuSharpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSharpenActionPerformed
        imgOperations = img;
        Kernel kernel = new Kernel(3, 3, new float[] { -1, -1, -1, -1, 9, -1, -1,
        -1, -1 });
        BufferedImageOp op = new ConvolveOp(kernel);
        img = imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuSharpenActionPerformed
    
    private void menuBlurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBlurActionPerformed
        imgOperations = img;
        Kernel kernel = new Kernel(3, 3, new float[] { 1f / 9f, 1f / 9f, 1f / 9f,
        1f / 9f, 1f / 9f, 1f / 9f, 1f / 9f, 1f / 9f, 1f / 9f });
        BufferedImageOp op = new ConvolveOp(kernel);
        img=imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuBlurActionPerformed

    private void menuRotateClockwiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRotateClockwiseActionPerformed
        imgOperations = img;
        AffineTransform tx = new AffineTransform();
        tx.rotate(Math.PI/2, imgOperations.getWidth() / 2, imgOperations.getHeight() / 2);

        AffineTransformOp op = new AffineTransformOp(tx,AffineTransformOp.TYPE_BILINEAR);
        img=imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuRotateClockwiseActionPerformed

    private void menuRotateCounterClockwiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRotateCounterClockwiseActionPerformed
        imgOperations = img;
        AffineTransform tx = new AffineTransform();
        tx.rotate(-Math.PI/2, imgOperations.getWidth() / 2, imgOperations.getHeight() / 2);

        AffineTransformOp op = new AffineTransformOp(tx,AffineTransformOp.TYPE_BILINEAR);
        img=imgOperations;
        img = op.filter(img, null);
    }//GEN-LAST:event_menuRotateCounterClockwiseActionPerformed

    private void menuColorCorrectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorCorrectionActionPerformed

    }//GEN-LAST:event_menuColorCorrectionActionPerformed

    private void menuHueSaturationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHueSaturationActionPerformed

    }//GEN-LAST:event_menuHueSaturationActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuPencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPencilActionPerformed
        drawable= !drawable;
	}//GEN-LAST:event_menuPencilActionPerformed

    private void menuClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearAllActionPerformed
        jPanel.removeAll();
        jPanel.updateUI();
        imgHeight = 300;
        imgWidth = 300;
        img = new BufferedImage(imgWidth,imgHeight,BufferedImage.TYPE_INT_ARGB );
        Dimension d = new Dimension(imgWidth,imgHeight);
        jPanel.setSize(d);
    }//GEN-LAST:event_menuClearAllActionPerformed
	
    private void menuPickColorActionPerformed(java.awt.event.ActionEvent evt) {                                                                                        
        Color currentColor=gfx.getColor();
        Color change = JColorChooser.showDialog(null, "Wybór koloru Ołówka", currentColor);
        gfx.setColor(change);
    }                                               

    //ta litania poleceń służy do zapewnienia odpowiedniego odświeżania
    private void menuDeselected(javax.swing.event.MenuEvent evt) {                                
        bRefreshing=true;
    }                               
	
	private void menu2Deselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuDeselected
        bRefreshing=true;
    }//GEN-LAST:event_menuDeselected

    private void menuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuKeyReleased
        bRefreshing=true;
    }//GEN-LAST:event_menuKeyReleased

    private void menu2KeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menu2KeyReleased
        bRefreshing=true;
    }//GEN-LAST:event_menu2KeyReleased
        
    private void menu3KeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menu3KeyReleased
       bRefreshing=true; 
    }//GEN-LAST:event_menu3KeyReleased

    private void menu3Deselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu3Deselected
        bRefreshing=true;
    }//GEN-LAST:event_menu3Deselected

	private void MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MenuSelected
        bRefreshing=false;
    }//GEN-LAST:event_MenuSelected

    private void menu2Selected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu2Selected
        bRefreshing=false;
    }//GEN-LAST:event_menu2Selected

    private void menu3Selected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu3Selected
        bRefreshing=false;
    }//GEN-LAST:event_menu3Selected
    //koniec litanii

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JFileChooser fileOpenChooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuBlur;
    private javax.swing.JMenuItem menuClearAll;
    private javax.swing.JMenuItem menuColorCorrection;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuHueSaturation;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuPencil;
    private javax.swing.JMenuItem menuPickColor;
    private javax.swing.JMenuItem menuRotateClockwise;
    private javax.swing.JMenuItem menuRotateCounterClockwise;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSharpen;
    // End of variables declaration//GEN-END:variables
}
